### ISSUE TITLE
[NEIAddons.17][Forestry unstable.485] Trees module doesn't work - no recipe/mutations.

### ISSUE THREAD

**Issue by MrGraphic** [bdew-minecraft/neiaddons#26]
From logs:
http://pastebin.com/TWPafk37
I did not tried with last stable version but it was working in older version so I assume that will also work
with such old one as the last stable.

**Comment by bdew** [comment]
Try with this build: http://jenkins.bdew.net/job/neiaddons-1.7.10/18/artifact/build/libs/neiaddons-mc1710-1.12.6.18.jar

The error is caused by forestry or one of the other mods putting bad data in the API. With this fix you will get a warning that will name the species that has bad data instead of a crash - please report it to it's author.

**Comment by MrGraphic** [comment]
To clarify that NPE was non fatal one so everything was working perfectly fine except trees module ( nei recipes ). 
Now about .18 - thanks man, tree module works as expected and same for your "blaming" code :)
http://pastebin.com/JpsvYie5
Unfortunelly it may take time to fix these as both Arkandos and Coder J are MIA.
Thanks one more time.

**Comment by bdew** [comment]
Glad to hear that it helped and hopefully the authors will be back at some point to fix their stuff
