### ISSUE TITLE
Crash when looking up usage for forestry sapling

### ISSUE THREAD

**Issue by nulano** [bdew-minecraft/neiaddons#9]
I'm not sure where to post this, so I'm posting it here.

I right-clicked (to lookup usage recipes) on a forestry sapling (id 13384 in FTB DW20 1.6.4 pack) and MC crashed.
Crash report (client): http://pastebin.com/kD9EDu76

**Comment by bdew** [comment]
This is likely caused by one of the other forestry addons putting bad data in, which sapling does it happen with?

I added a check on my side to prevent the crash, can you test with this version: http://jenkins.bdew.net/job/neiaddons/lastSuccessfulBuild/artifact/build/libs/neiaddons-mc164-1.10.1.56.jar and see if it fixes the crash?

**Comment by nulano** [comment]
It didn't fix the crash.

Video demonstrating the crash: http://youtu.be/jk9sf8izxr4

**Comment by bdew** [comment]
Ok i think i understand what's going on, please check this version - http://jenkins.bdew.net/job/neiaddons/lastSuccessfulBuild/artifact/build/libs/neiaddons-mc164-1.10.1.57.jar - i'm pretty sure it will prevent that crash.

**Comment by nulano** [comment]
That fixed the crash.
